## EDITOR UI COLORS

"ui.background" = { }
"ui" = { }
# "ui.text" = "white"
"ui.window" = "ruler"

# Debug
"ui.debug.active" = "green"
"ui.debug.breakpoint" = "red"

# Popus and menus
"ui.menu" = { bg = "background" }
"ui.menu.scroll" = { modifiers = ["reversed"] }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.popup" = { bg = "background" }
"ui.popup.info" = { bg = "background" }
"ui.help" = { bg = "background" }
"ui.text.focus" = { fg = "highlight" }

# Gutter
"ui.gutter" = { bg = "none" }
"ui.linenr" = { bg = "none" }
"ui.linenr.selected" = { fg = "red", modifiers = ["bold"] }

# Cursor
"ui.cursor" = { modifiers = [ "reversed" ] }
"ui.cursor.primary" = { fg = "white", modifiers = [ "reversed" ] }
"ui.cursorcolumn.primary" = { bg = "black" }
"ui.cursorline.primary" = { bg = "black" }
"ui.selection" = { fg = "white", bg = "ruler" }
"ui.highlight" = { bg = "ruler" }

# Statusline
"ui.statusline" = {}
"ui.statusline.inactive" = { fg = "white", modifiers = ["dim"] }
"ui.statusline.insert" = { fg = "white", bg = "red" }
"ui.statusline.normal" = { fg = "white" }
"ui.statusline.select" = { fg = "white", bg = "green" }
"ui.statusline.separator" = "ruler"

# Virtual/invisible text
"ui.virtual.indent-guide" = { fg = "black" }
"ui.virtual.inlay-hint" = { fg = "gray", modifiers = ["italic"] }
"ui.virtual.whitespace" = { fg = "black" }
"ui.virtual.ruler" = { bg = "ruler" }
"ui.virtual.wrap" = { fg = "black" }
"ui.virtual.jump-label" = { fg = "black", bg = "purple", modifiers = ["italic", "bold"] }

# Bufferline
"ui.bufferline" = { }
"ui.bufferline.active" = { fg = "white", modifiers = ["bold", "reversed"] }

## SYNTAX HIGHLIGHTING
"comment" = { fg = "gray", modifiers = ["italic"] }
"label" = "gray"
"constructor" = "purple"
"namespace" = "blue"
"module" = "blue"
"operator" = "highlight"
"special" = "orange"
"tag" = "orange"

# Constants
"constant" = { fg = "orange", modifiers = ["bold"] }
"constant.builtin" = { fg = "orange", modifiers = ["bold", "italic"] }
"constant.builtin.boolean" = { fg = "orange", modifiers = ["italic"] }
"constant.builtin.character" = { fg = "green", modifiers = ["italic"] }
"constant.character" = "green"
"constant.character.escape" = "blue"
"constant.macro" = "blue"
"constant.numeric" = "orange"

# Diagnostics
"diagnostic" = { underline = { style = "dotted" } }
# "diagnostic" = { underline = { style = "dotted" } }
# "diagnostic" = { modifiers = ["reversed"] }
# "diagnostic.hint" = { underline = { style = "dotted" } }
# "diagnostic.info" = { underline = { style = "dotted" } }
# "diagnostic.warning" = { underline = { style = "dotted" } }
# "diagnostic.error" = { underline = { color = "#fc5d7c", style = "curl" } }

# Diagnostics (gutter)
"hint" = { fg = "gray", modifiers = ["italic", "dim"] }
"info" = { fg = "blue", modifiers = ["italic", "dim"] }
"warning" = { fg = "orange", modifiers = ["italic", "dim"] }
"error" = { fg = "red", modifiers = ["italic", "dim"] }

# Diffs
"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"

# Functions
"function" = "green"
"function.builtin" = { fg = "green", modifiers = ["italic"] }
"function.method" = "green"
"function.macro" = "green"
"function.special" = "green"

# Git
"git.delta.moved" = "gray"

# Keywords
"keyword" = { fg = "red", modifiers = ["italic"] }
"keyword.control.conditional" = { fg = "red", modifiers = ["italic"] }
"keyword.control.exception" = { fg = "red", modifiers = ["italic"] }
"keyword.control.repeat" = { fg = "red", modifiers = ["italic"] }
"keyword.directive" = { fg = "red", modifiers = ["italic"] }
"keyword.function" = { fg = "red", modifiers = ["italic"] }
"keyword.operator" = { fg = "red", modifiers = ["italic"] }
"keyword.return" = { fg = "red", modifiers = ["italic"] }
"keyword.storage.modifier" = { fg = "red", modifiers = ["italic"] }
"keyword.storage.type" = { fg = "red", modifiers = ["italic"] }

# Punctuation
"punctuation" = "white"
"punctuation.bracket" = "white"
"punctuation.delimiter" = "white"
"punctuation.special" = "white"

# Strings
"string" = "yellow"
"string.escape" = "cyan"
"string.regex" = "cyan"
"string.special" = "cyan"

# Types
"type" = "purple"
"type.builtin" = { fg = "purple", modifiers = ["italic"] }

# Variables
"variable" = "blue"
"variable.builtin" = { fg = "blue", modifiers = ["italic"] }
# "variable.parameter" = { fg = "blue", modifiers = ["bold"] }
"variable.parameter" = { fg = "cyan" }
"variable.other.member" = "orange"
"attribute" = "orange"

# Markup
"markup.document" = { "fg" = "white" }
"document" = { "fg" = "white" }
"markup.heading" = { modifiers = ["bold"] }
"markup.heading.1" = { fg = "red" }
"markup.heading.2" = { fg = "green" }
"markup.heading.3" = { fg = "cyan" }
"markup.heading.4" = { fg = "yellow" }
"markup.heading.5" = { fg = "purple" }
"markup.heading.6" = { fg = "fg" }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = { fg = "purple", modifiers = ["italic"] }
"markup.raw" = "yellow"

[palette]
# base16 colors
# They can be inherited from terminal config if desired by commenting this section out

# default = "default"
# black = "#181819"
# red = "#fc5d7c"
# green = "#9ed072"
# yellow = "#e7c664"
# blue = "#76cce0"
# blue = "#96dcf0"
# magenta = "???"
# cyan = "#8dd0b6" # added for compatibility with `edge` scheme
# gray = "#7f8490"
# gray = "#808080"
# light-red = "#fc5d7c"
# light-green = "#9ed072"
# light-yellow = "#e7c664"
# light-blue = "#76cce0"
# light-magenta = "#7600e0"
# light-cyan = "#8dd0b6"
# light-gray = "#7f8490"
# white = "???"

# These are other custom colors
background = "#0f111a"
highlight = "#ffffff"
ruler = "#404060"
orange = "#FF7400"
purple = "#b39df3"

