alias l='lsd -lAgF --tree --depth 2 --permission rwx --date +%Y-%m-%d --group-dirs last --truncate-owner-after 3'
alias lg='lazygit'
alias x='joshuto'
alias c='z'
alias cb='~/isomorphic_copy/bin/c'
alias p='~/isomorphic_copy/bin/p'
alias td='todo.sh'
alias dps="docker ps -a --format json | jq -r '.Names, .RunningFor, .Status' | paste - - - | column -ts $'\t' | sort"
alias ai='clear;tgpt -m'
alias web='sr google'
# alias web='sr google -browser=w3m'
