platform_plugin: auto
renderer:
    backend: OpenGL
    tile_hashtable_slots: 4096
    tile_cache_count: 4000
    tile_direct_mapping: true
word_delimiters: " /\\()\"'-.,:;<>~!@#$%^&*+=[]{}~?|│"
read_buffer_size: 16384
pty_buffer_size: 1048576
default_profile: main
spawn_new_process: false
reflow_on_resize: true
bypass_mouse_protocol_modifier: Shift
mouse_block_selection_modifier: Control
on_mouse_select: CopyToSelectionClipboard
live_config: true
images:
    sixel_scrolling: true
    sixel_register_count: 4096
    max_width: 0
    max_height: 0
profiles:
    main:
      fullscreen: false
      maximized: true
      scrollbar:
        position: Hidden
      margins:
        horizontal: 0
        vertical: 0
      background:
        opacity: 1.0
        blur: true
      font:
        size: 13
        # dpi_scale: 1.0
        # locator: native
        # text_shaping:
        #   engine: native
        # builtin_box_drawing: true
        # render_mode: gray
        # strict_spacing: true
        regular:
          family: "JetBrainsMono Nerd Font Propo"
          # weight: regular
          # slant: normal
          # features: []
        emoji: "emoji"
      colors: "nautilus"
      bell:
        sound: "off"
        alert: false
      shell: "/home/linuxbrew/.linuxbrew/bin/nu"
color_schemes:
  nautilus:
    default:
      background: '#090B10'
      foreground: '#C0A0C0'
    cursor:
      default: CellForeground
      text: CellBackground
    hyperlink_decoration:
      normal: '#f0f000'
      hover: '#ff0000'
    vi_mode_highlight:
      foreground: CellForeground
      foreground_alpha: 1.0
      background: '#ffa500'
      background_alpha: 0.5
    vi_mode_cursorline:
      foreground: '#ffffff'
      foreground_alpha: 0.2
      background: '#808080'
      background_alpha: 0.4
    selection:
      foreground: CellForeground
      foreground_alpha: 1.0
      background: '#603048'
      background_alpha: 0.5
    search_highlight:
      foreground: CellBackground
      background: CellForeground
      foreground_alpha: 1.0
      background_alpha: 1.0
    search_highlight_focused:
      foreground: CellBackground
      background: CellForeground
      foreground_alpha: 1.0
      background_alpha: 1.0
    word_highlight_current:
      foreground: CellForeground
      background: '#909090'
      foreground_alpha: 1.0
      background_alpha: 0.5
    word_highlight_other:
      foreground: CellForeground
      background: '#909090'
      foreground_alpha: 1.0
      background_alpha: 0.5
    indicator_statusline:
      foreground: '#808080'
      background: '#000000'
    indicator_statusline_inactive:
      foreground: '#808080'
      background: '#000000'
    input_method_editor:
      foreground: '#FFFFFF'
      background: '#FF0000'
    normal:
      black: '#373A55'
      red: '#FF0094'
      green: '#B6FF00'
      yellow: '#FFC000'
      blue: '#558CFF'
      magenta: '#8D82FF'
      cyan: '#00B6FF'
      white: '#E2DDC8'
    bright:
      black: '#575A75'
      red: '#FF51B6'
      green: '#C3E88D'
      yellow: '#FFD964'
      blue: '#82AAFF'
      magenta: '#D1CCFF'
      cyan: '#89DDFF'
      white: '#FFFFFF'
    # Disabled due to stretch behaviour
    background_image:
      path: '~/Pictures/wallpapers/target'
      opacity: 1
      blur: True

input_mapping:
  # - { mods: [Control], key: Enter, action: CancelSelection }
  # - { mods: [Control], key: Enter, action: ChangeProfile }
  # - { mods: [Control], key: Enter, action: ClearHistoryAndReset }
  # - { mods: [Control], key: Enter, action: CopyPreviousMarkRange }
  # - { mods: [Control], key: Enter, action: CopySelection }
  # - { mods: [Control], key: Enter, action: CreateDebugDump }
  # - { mods: [Control, Shift], key: Space, action: CreateSelection, delimiters: '' }
  - { mods: [Control], key: '-', action: DecreaseFontSize }
  # - { mods: [Control], key: Enter, action: DecreaseOpacity }
  # - { mods: [Control], key: Enter, action: FocusNextSearchMatch }
  # - { mods: [Control], key: Enter, action: FocusPreviousSearchMatch }
  # - { mods: [Control], key: Enter, action: FollowHyperlink }
  - { mods: [Control], key: '=', action: IncreaseFontSize }
  # - { mods: [Control], key: Enter, action: IncreaseOpacity }
  # - { mods: [Control], key: Enter, action: NewTerminal }
  # - { mods: [Control], key: Enter, action: NoSearchHighlight }
  # - { mods: [Control], key: Enter, action: OpenConfiguration }
  # - { mods: [Control], key: Enter, action: OpenFileManager }
  # - { mods: [Control], key: Enter, action: OpenSelection }
  - { mods: [Control], key: V, action: PasteClipboard }
  # - { mods: [Control], key: Enter, action: PasteSelection }
  # - { mods: [Control], key: Enter, action: Quit }
  # - { mods: [Control], key: Enter, action: ReloadConfig }
  # - { mods: [Control], key: Enter, action: ResetConfig }
  - { mods: [Control], key: '0', action: ResetFontSize }
  # - { mods: [Control], key: Enter, action: ScreenshotVT }
  # - { mods: [Control], key: Enter, action: SaveScreenshot }
  # - { mods: [Control], key: Enter, action: CopyScreenshot }
  # - { mods: [Control], key: Enter, action: ScrollDown }
  # - { mods: [Control], key: Enter, action: ScrollMarkDown }
  # - { mods: [Control], key: Enter, action: ScrollMarkUp }
  # - { mods: [Control], key: Enter, action: ScrollOneDown }
  # - { mods: [Control], key: Enter, action: ScrollOneUp }
  # - { mods: [Control], key: Enter, action: ScrollPageDown }
  # - { mods: [Control], key: Enter, action: ScrollPageUp }
  # - { mods: [Control], key: Enter, action: ScrollToBottom }
  # - { mods: [Control], key: Enter, action: ScrollToTop }
  # - { mods: [Control], key: Enter, action: ScrollUp }
  # - { mods: [Control], key: Enter, action: SearchReverse }
  # - { mods: [Control], key: Enter, action: SendChars }
  # - { mods: [Control], key: Enter, action: ToggleAllKeyMaps }
  # - { mods: [Control], key: Enter, action: ToggleFullscreen }
  # - { mods: [Control], key: Enter, action: ToggleInputProtection }
  # - { mods: [Control], key: Enter, action: ToggleStatusLine }
  # - { mods: [Control], key: Enter, action: ToggleTitleBar }
  # - { mods: [Control], key: Enter, action: TraceBreakAtEmptyQueue }
  # - { mods: [Control], key: Enter, action: TraceEnter }
  # - { mods: [Control], key: Enter, action: TraceLeave }
  # - { mods: [Control], key: Enter, action: TraceStep }
  - { mods: [Control, Shift], key: Space, action: ViNormalMode }
  # - { mods: [Control], key: Enter, action: WriteScreen, chars: '' }
  # - { mods: [Control], key: Enter, action: CreateNewTab }
  # - { mods: [Control], key: Enter, action: CloseTab }
  # - { mods: [Control], key: Enter, action: MoveTabTo, position: 0 }
  # - { mods: [Control], key: Enter, action: MoveTabToLeft }
  # - { mods: [Control], key: Enter, action: MoveTabToRight }
  # - { mods: [Control], key: Enter, action: SwitchToTab, position: 0 }
  # - { mods: [Control], key: Enter, action: SwitchToPreviousTab }
  # - { mods: [Control], key: Enter, action: SwitchToTabLeft }
  # - { mods: [Control], key: Enter, action: SwitchToTabRight }
