
[[Snippets]]
  Description = "greppable docker logs"
  Output = ""
  Tag = []
  command = "docker logs -t --since 24h %q 2>&1"

[[Snippets]]
  Description = "Show listening ports"
  Output = ""
  Tag = []
  command = "ss -tulpn"

[[Snippets]]
  Description = "Dump Python Object"
  Output = ""
  Tag = []
  command = '''    from pathlib import Path
    from json import dumps

    Path("/tmp/case_data.json").write_text(dumps(case_data, indent=2))
    breakpoint()
'''

