
[[Snippets]]
  Description = "greppable docker logs"
  Output = ""
  Tag = []
  command = "docker logs -t --since 24h <container_name> 2>&1"

[[Snippets]]
  Description = "Show listening ports"
  Output = ""
  Tag = []
  command = "ss -tulpn"

[[Snippets]]
  Description = "Dump Python Object"
  Output = ""
  Tag = []
  command = '''from pathlib import Path; from json import dumps; Path("/tmp/tmp.json").write_text(dumps(<variable_name>, indent=2));'''
