# [[language]]
# name = "python"
# scope = "source.python"
# injection-regex = "python"
# file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct", "rpy", "cpy", "ipy", "pyt", "SConscript"]
# shebangs = ["python"]
# roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
# comment-token = "#"
# # language-servers = ["ruff"]
# language-servers = ["ruff-lsp"]
# indent = { tab-width = 4, unit = "    " }
# auto-format = true
# rulers = [80, 120]

# [language.formatter]
# command = "ruff"
# args = [
#   "format"
# ]

# [language-server.ruff]
# command = "ruff-lsp"

# [language-server.ruff.config]
# settings = {args = []}

# [language-server.pyright.config]
# reportMissingTypeStubs = false

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"
# autoImportCompletions = true

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.ruff-lsp.config]
documentFormatting = true 
settings.run = "onSave"

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]
config.reportMissingtypeStubs = false

[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[[language]]
name = "python"
auto-format = true
file-types = ["py"]
language-servers = [
  { name = "ruff-lsp", only-features = [ "format", "diagnostics" ] },
  { name = "pyright", except-features = [ "format", "diagnostics" ] },
  { name = "cspell"},
]
