# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Helpful symbols
# 🔴🟢
# 

add_newline = false

# format = """$all"""
format = """
$status\
$container\
$shell\
$shlvl\
[ ]()\
$directory\
$direnv\
$git_branch\
$git_status\
[ ]()\
$hostname\
$os\
[ ]()\
$username\
$sudo\
$docker_context\
$nodejs\
$package\
$python\
$rust\
$fill\
$cmd_duration\
[ ]()\
$time\
$character\
"""

[line_break]
disabled = false

[status]
disabled = false
# symbol = '[](fg:'
# success_symbol = ''
# symbol = '🔴'
# symbol = '[🔴](bg:#ffffff)'
# symbol = '[](bg:none fg:#fc5d7c)[$status](bold fg:#000000 bg:#fc5d7c)'
# symbol = '[$status](bold fg:#fc5d7c)'
# symbol = '[$status](bold fg:#fc5d7c) '
symbol = '[$status $common_meaning](bold fg:red) '
# success_symbol = '🟢'
# success_symbol = '[](bg:none fg:#9ed072)[$status ](fg:#000000 bg:#9ed072)'
# success_symbol = '[$status](fg:#9ed072)'
# map_symbol = true
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
format = '$symbol'
# style = 'fg: #000000 '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)[](fg:#85d3f2 bg:none)'
# format = '$symbol$common_meaning$signal_name$maybe_int'
# format = '[](bg:none fg:#bbbbbb)[ $symbol $status ]($style)'
# map_symbol = true
# style = 'fg: #000000 bg:#444444'
# style = 'bg:#bbbbbb'

[time]
disabled = false
# format="[🕒 $time]($style)"
# format="[$time]($style)"
format="$time"
# time_format = "%T%z" #change to %R to only have HH:MM
# time_format = "%R%z" #change to %R to only have HH:MM
# time_format = "%Z %#z"
time_format = "%T%z"
# style = "#808080"

[username]
style_user = "fg:blue"
style_root = "bold fg:red"
# format = "[🧑 $user]($style)"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = '🌎'
format = "[$hostname]($style)$ssh_symbol"
disabled = false
style = "fg:cyan"

[os]
format = "[$symbol ]($style)"
style = "bold cyan"
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[docker_context]
only_with_files = false
format = '  $context'
disabled = false

[localip]
disabled = true
ssh_only = false
# format = "[ 🌐 ($localipv4) ]($style)"
format = " [($localipv4) ]($style)"
style = "fg:purple"

[character]
success_symbol = "\n▶"
error_symbol = "\n[▶](fg:red)"
# success_symbol = "\n[➤](white)"
# error_symbol = "\n[➤](red)"
# success_symbol = "\n[❱](white)"
# error_symbol = "\n[❱](red)"
# success_symbol = "[->](white)"
# error_symbol = "[->](red)"
# success_symbol = "\n[➜](white)"
# error_symbol = "\n[➜](red)"
# success_symbol = "\n[](white)"
# error_symbol = "\n[](red)"
# success_symbol = "\n[](white)"
# error_symbol = "\n[](red)"
# success_symbol = ""
# error_symbol = ""

[git_branch]
# symbol = "🌱 "
truncation_length = 8
truncation_symbol = "…"
# ignore_branches = ["master", "main"]
# Icons: 
format = " [$branch]($style)"
style = "fg:green"

# [git_commit]
# disabled = false
# # commit_hash_length = 4
# # tag_symbol = "🔖 "
# # format = "[\\($hash\\) \\($tag\\)]($style)"
# format = "[\\($tag\\)]($style)"
# style = "fg:#9ed072"

[git_status]
# # format="[](fg:#ffffff bg:none)[🥶](fg:#282c34 )[ ](fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[](fg:#4da0ff bg:none)"
# # format="(fg:#ffffff )[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )[](fg:#9ed072 bg:none)"
# format="[$modified](fg:#282c34 )[$untracked](fg:#282c34 )[$staged](fg:#282c34 )[$renamed](fg:#282c34 )"
style = "fg:green"
format="[$all_status$ahead_behind]($style)"
conflicted = "⚠ "
ahead = " "
behind = " "
diverged = " "
up_to_date = ""
untracked = " "
stashed = " "
modified = " "
renamed = " "
deleted = " "
# style = "fg:#9ed072"
disabled = false

# [git_state]
# rebase = "REBASING"
# merge =	"MERGING"
# revert = "REVERTING"
# cherry_pick = "CHERRY-PICKING"
# bisect = "BISECTING"
# am = "AM"
# am_or_rebase = "AM/REBASE"
# style =	"yellow"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# disabled = false

[directory]
# format = "[📂 $path ]($style)"
# truncate_to_repo = true
# fish_style_pwd_dir_length = 2
format = "[$path]($style)"
style = "fg:yellow"
truncation_length = 2
# truncation_symbol = "…"

[package] 
symbol = "📦"
disabled = true
style = "fg:#000000 "

[python]
symbol = ""
format = ' ${symbol} ${pyenv_prefix}(${version})( \($virtualenv\))'

[rust]
symbol = "🦀"
format = ' [$symbol $version]($style)'
style = "fg:#f39660"

[fill]
symbol = ' '

# [custom.emoji]
# description = "Displays a (pseudo) random emoji for each prompt"
# command = "EMOJIS=(⛵️ 🛰 🪐 🚀 🧡 🔭 🌍 💫 ☄️ ✨ 🌠 🌌 ⭐️); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# when = "1"
# shell = ["cmd /C"]
# format = "$output"

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = '$duration'

[shlvl]
disabled = false
style = "fg:#ff7400"
format = '[+$shlvl]($style)'
threshold = 2

[sudo]
disabled = false
# format = '[*](blue)'
format = '[💪](blue)'

[container]
style = "fg:#ff7400"
format = '[⬢]($style)'

[direnv]
style = "fg:yellow bold"
format = "[$loaded]($style)"
allowed_msg     = "+"   # The message displayed when an rc file is allowed.
not_allowed_msg = "❌" # The message displayed when an rc file is not_allowed.
denied_msg      = "❌" # The message displayed when an rc file is denied.
loaded_msg      = " "  # The message displayed when an rc file is loaded.
unloaded_msg    = "❌" # The message displayed when an rc file is not loaded.
disabled = false


# ~/.config/starship.toml

[shell]
fish_indicator = '🐟'
nu_indicator = 'nu'
bash_indicator = '_'
unknown_indicator = 'UNKNOWN SHELL'
style = "fg:#ff7400 bold"
format = "[$indicator]($style)"
disabled = false
