foreground= #C0A0C0
background= #090B10
cursor=     #C0A0C0

color0=     #373A55
color1=     #FF0094
color2=     #B6FF00
color3=     #FFC000
color4=     #558CFF
color5=     #8D82FF
color6=     #00B6FF
color7=     #E2DDC8

color8=     #575A75
color9=     #FF51B6
color10=    #C3E88D
color11=    #FFD964
color12=    #82AAFF
color13=    #D1CCFF
color14=    #89DDFF
color15=    #FFFFFF

color16=    #d08770
color17=    #ab7967
color18=    #343d46
color19=    #4f5b66
color20=    #a7adba
color21=    #dfe1e8
